/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { ApplyTokenResponseAdditionalInfo } from './ApplyTokenResponseAdditionalInfo';
import {
    validateApplyTokenResponseAdditionalInfo,
    ApplyTokenResponseAdditionalInfoFromJSON,
    ApplyTokenResponseAdditionalInfoFromJSONTyped,
    ApplyTokenResponseAdditionalInfoToJSON,
    ApplyTokenResponseAdditionalInfoToJSONTyped,
} from './ApplyTokenResponseAdditionalInfo';

/**
 * 
 * @export
 * @interface ApplyTokenResponse
 */
export interface ApplyTokenResponse {
    /**
     * Refer to response code list:<br>
     * * 2007400 - Successful<br>
     * * 4007400 - Bad Request - Retry request with proper parameter<br>
     * * 4007401 - Invalid Field Format - Retry request with proper parameter<br>
     * * 4007402 - Invalid Mandatory Field - Retry request with proper parameter<br>
     * * 4017400 - Unauthorized. [reason] - Retry request with proper parameter<br>
     * * 4297400 - Too Many Requests - Retry request periodically by sending same request payload<br>
     * * 5007400 - General Error - Retry request periodically<br>
     * * 5007401 - Internal Server Error - Retry request periodically by sending same request payload<br>
     * 
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    responseCode: string;
    /**
     * Refer to response code list
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    responseMessage: string;
    /**
     * Token type
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    tokenType?: string;
    /**
     * Access token that can be used as user authorization
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    accessToken: string;
    /**
     * Access token expiry time
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    accessTokenExpiryTime?: string;
    /**
     * Token that can be used to refresh the accessToken when it expires
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    refreshToken?: string;
    /**
     * Refresh token expiry time
     * @type {string}
     * @memberof ApplyTokenResponse
     */
    refreshTokenExpiryTime?: string;
    /**
     * 
     * @type {ApplyTokenResponseAdditionalInfo}
     * @memberof ApplyTokenResponse
     */
    additionalInfo?: ApplyTokenResponseAdditionalInfo;
}

/**
 * Check if a given object implements the ApplyTokenResponse interface.
 */
export function instanceOfApplyTokenResponse(value: object): value is ApplyTokenResponse {
    if (!('responseCode' in value) || value['responseCode'] === undefined) return false;
    if (!('responseMessage' in value) || value['responseMessage'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function ApplyTokenResponseFromJSON(json: any): ApplyTokenResponse {
    return ApplyTokenResponseFromJSONTyped(json, false);
}

export function ApplyTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'responseCode': json['responseCode'],
        'responseMessage': json['responseMessage'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'accessToken': json['accessToken'],
        'accessTokenExpiryTime': json['accessTokenExpiryTime'] == null ? undefined : json['accessTokenExpiryTime'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpiryTime': json['refreshTokenExpiryTime'] == null ? undefined : json['refreshTokenExpiryTime'],
        'additionalInfo': json['additionalInfo'] == null ? undefined : ApplyTokenResponseAdditionalInfoFromJSON(json['additionalInfo']),
    };
}

export function ApplyTokenResponseToJSON(json: any): ApplyTokenResponse {
    return ApplyTokenResponseToJSONTyped(json, false);
}

export function ApplyTokenResponseToJSONTyped(value?: ApplyTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseCode': value['responseCode'],
        'responseMessage': value['responseMessage'],
        'tokenType': value['tokenType'],
        'accessToken': value['accessToken'],
        'accessTokenExpiryTime': value['accessTokenExpiryTime'],
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiryTime': value['refreshTokenExpiryTime'],
        'additionalInfo': ApplyTokenResponseAdditionalInfoToJSON(value['additionalInfo']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    responseCode: {
        maxLength: 7,
    },
    responseMessage: {
        maxLength: 150,
    },
    accessTokenExpiryTime: {
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
    },
    refreshTokenExpiryTime: {
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
    },
}

export function validateApplyTokenResponse(value: ApplyTokenResponse): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseCode', value.responseCode, propertyValidationAttributesMap['responseCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseMessage', value.responseMessage, propertyValidationAttributesMap['responseMessage']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('accessTokenExpiryTime', value.accessTokenExpiryTime, propertyValidationAttributesMap['accessTokenExpiryTime']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('refreshTokenExpiryTime', value.refreshTokenExpiryTime, propertyValidationAttributesMap['refreshTokenExpiryTime']));

    validationErrorContexts.push(...validateApplyTokenResponseAdditionalInfo(value.additionalInfo));

    return validationErrorContexts;
}
