/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface PayOptionInfo
 */
export interface PayOptionInfo {
    /**
     * Payment method name
     * @type {string}
     * @memberof PayOptionInfo
     */
    payMethod: PayOptionInfoPayMethodEnum;
    /**
     * Payment provider name
     * @type {string}
     * @memberof PayOptionInfo
     */
    payOption?: PayOptionInfoPayOptionEnum;
    /**
     * 
     * @type {Money}
     * @memberof PayOptionInfo
     */
    payAmount?: Money;
    /**
     * 
     * @type {Money}
     * @memberof PayOptionInfo
     */
    transAmount?: Money;
    /**
     * 
     * @type {Money}
     * @memberof PayOptionInfo
     */
    chargeAmount?: Money;
    /**
     * Extended bill information for pay option
     * @type {string}
     * @memberof PayOptionInfo
     */
    payOptionBillExtendInfo?: string;
    /**
     * Additional extend information
     * @type {string}
     * @memberof PayOptionInfo
     */
    extendInfo?: string;
    /**
     * Payment code
     * @type {string}
     * @memberof PayOptionInfo
     */
    paymentCode?: string;
}


/**
 * @export
 */
export const PayOptionInfoPayMethodEnum = {
    Balance: 'BALANCE',
    Coupon: 'COUPON',
    NetBanking: 'NET_BANKING',
    CreditCard: 'CREDIT_CARD',
    DebitCard: 'DEBIT_CARD',
    VirtualAccount: 'VIRTUAL_ACCOUNT',
    Otc: 'OTC',
    DirectDebitCreditCard: 'DIRECT_DEBIT_CREDIT_CARD',
    DirectDebitDebitCard: 'DIRECT_DEBIT_DEBIT_CARD',
    OnlineCredit: 'ONLINE_CREDIT',
    LoanCredit: 'LOAN_CREDIT'
} as const;
export type PayOptionInfoPayMethodEnum = typeof PayOptionInfoPayMethodEnum[keyof typeof PayOptionInfoPayMethodEnum];

/**
 * @export
 */
export const PayOptionInfoPayOptionEnum = {
    NetworkPayPgSpay: 'NETWORK_PAY_PG_SPAY',
    NetworkPayPgOvo: 'NETWORK_PAY_PG_OVO',
    NetworkPayPgGopay: 'NETWORK_PAY_PG_GOPAY',
    NetworkPayPgLinkaja: 'NETWORK_PAY_PG_LINKAJA',
    NetworkPayPgCard: 'NETWORK_PAY_PG_CARD',
    VirtualAccountBca: 'VIRTUAL_ACCOUNT_BCA',
    VirtualAccountBni: 'VIRTUAL_ACCOUNT_BNI',
    VirtualAccountMandiri: 'VIRTUAL_ACCOUNT_MANDIRI',
    VirtualAccountBri: 'VIRTUAL_ACCOUNT_BRI',
    VirtualAccountBtpn: 'VIRTUAL_ACCOUNT_BTPN',
    VirtualAccountCimb: 'VIRTUAL_ACCOUNT_CIMB',
    VirtualAccountPermata: 'VIRTUAL_ACCOUNT_PERMATA'
} as const;
export type PayOptionInfoPayOptionEnum = typeof PayOptionInfoPayOptionEnum[keyof typeof PayOptionInfoPayOptionEnum];


/**
 * Check if a given object implements the PayOptionInfo interface.
 */
export function instanceOfPayOptionInfo(value: object): value is PayOptionInfo {
    if (!('payMethod' in value) || value['payMethod'] === undefined) return false;
    return true;
}

export function PayOptionInfoFromJSON(json: any): PayOptionInfo {
    return PayOptionInfoFromJSONTyped(json, false);
}

export function PayOptionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayOptionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'payMethod': json['payMethod'],
        'payOption': json['payOption'] == null ? undefined : json['payOption'],
        'payAmount': json['payAmount'] == null ? undefined : MoneyFromJSON(json['payAmount']),
        'transAmount': json['transAmount'] == null ? undefined : MoneyFromJSON(json['transAmount']),
        'chargeAmount': json['chargeAmount'] == null ? undefined : MoneyFromJSON(json['chargeAmount']),
        'payOptionBillExtendInfo': json['payOptionBillExtendInfo'] == null ? undefined : json['payOptionBillExtendInfo'],
        'extendInfo': json['extendInfo'] == null ? undefined : json['extendInfo'],
        'paymentCode': json['paymentCode'] == null ? undefined : json['paymentCode'],
    };
}

export function PayOptionInfoToJSON(json: any): PayOptionInfo {
    return PayOptionInfoToJSONTyped(json, false);
}

export function PayOptionInfoToJSONTyped(value?: PayOptionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payMethod': value['payMethod'],
        'payOption': value['payOption'],
        'payAmount': MoneyToJSON(value['payAmount']),
        'transAmount': MoneyToJSON(value['transAmount']),
        'chargeAmount': MoneyToJSON(value['chargeAmount']),
        'payOptionBillExtendInfo': value['payOptionBillExtendInfo'],
        'extendInfo': value['extendInfo'],
        'paymentCode': value['paymentCode'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    payMethod: {
        maxLength: 64,
    },
    payOption: {
        maxLength: 64,
    },
    payOptionBillExtendInfo: {
        maxLength: 4096,
    },
    extendInfo: {
        maxLength: 4096,
    },
    paymentCode: {
        maxLength: 64,
    },
}

export function validatePayOptionInfo(value: PayOptionInfo): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('payMethod', value.payMethod, propertyValidationAttributesMap['payMethod']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('payOption', value.payOption, propertyValidationAttributesMap['payOption']));

    validationErrorContexts.push(...validateMoney(value.payAmount));

    validationErrorContexts.push(...validateMoney(value.transAmount));

    validationErrorContexts.push(...validateMoney(value.chargeAmount));

    validationErrorContexts.push(...ValidationUtil.validateProperty('payOptionBillExtendInfo', value.payOptionBillExtendInfo, propertyValidationAttributesMap['payOptionBillExtendInfo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('extendInfo', value.extendInfo, propertyValidationAttributesMap['extendInfo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('paymentCode', value.paymentCode, propertyValidationAttributesMap['paymentCode']));

    return validationErrorContexts;
}
