/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { BankAccountInquiryResponseAdditionalInfo } from './BankAccountInquiryResponseAdditionalInfo';
import {
    validateBankAccountInquiryResponseAdditionalInfo,
    BankAccountInquiryResponseAdditionalInfoFromJSON,
    BankAccountInquiryResponseAdditionalInfoFromJSONTyped,
    BankAccountInquiryResponseAdditionalInfoToJSON,
    BankAccountInquiryResponseAdditionalInfoToJSONTyped,
} from './BankAccountInquiryResponseAdditionalInfo';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface BankAccountInquiryResponse
 */
export interface BankAccountInquiryResponse {
    /**
     * Refer to response code list
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    responseCode: string;
    /**
     * Refer to response code list
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    responseMessage: string;
    /**
     * Transaction identifier on DANA system
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    referenceNo?: string;
    /**
     * Unique transaction identifier on partner system which assigned to each transaction<br>
     * Notes:<br>
     * If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before
     * 
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    partnerReferenceNo?: string;
    /**
     * Customer account type
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    accountType?: string;
    /**
     * Beneficiary account number
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    beneficiaryAccountNumber: string;
    /**
     * Beneficiary account name
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    beneficiaryAccountName: string;
    /**
     * Beneficiary Bank code
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    beneficiaryBankCode?: string;
    /**
     * Beneficiary Bank short name
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    beneficiaryBankShortName?: string;
    /**
     * Beneficiary Bank name
     * @type {string}
     * @memberof BankAccountInquiryResponse
     */
    beneficiaryBankName?: string;
    /**
     * Amount. Contains two sub-fields:<br>
     * 1. Value: Transaction amount, including the cents<br>
     * 2. Currency: Currency code based on ISO
     * 
     * @type {Money}
     * @memberof BankAccountInquiryResponse
     */
    amount: Money;
    /**
     * 
     * @type {BankAccountInquiryResponseAdditionalInfo}
     * @memberof BankAccountInquiryResponse
     */
    additionalInfo?: BankAccountInquiryResponseAdditionalInfo;
}

/**
 * Check if a given object implements the BankAccountInquiryResponse interface.
 */
export function instanceOfBankAccountInquiryResponse(value: object): value is BankAccountInquiryResponse {
    if (!('responseCode' in value) || value['responseCode'] === undefined) return false;
    if (!('responseMessage' in value) || value['responseMessage'] === undefined) return false;
    if (!('beneficiaryAccountNumber' in value) || value['beneficiaryAccountNumber'] === undefined) return false;
    if (!('beneficiaryAccountName' in value) || value['beneficiaryAccountName'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function BankAccountInquiryResponseFromJSON(json: any): BankAccountInquiryResponse {
    return BankAccountInquiryResponseFromJSONTyped(json, false);
}

export function BankAccountInquiryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountInquiryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'responseCode': json['responseCode'],
        'responseMessage': json['responseMessage'],
        'referenceNo': json['referenceNo'] == null ? undefined : json['referenceNo'],
        'partnerReferenceNo': json['partnerReferenceNo'] == null ? undefined : json['partnerReferenceNo'],
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
        'beneficiaryAccountNumber': json['beneficiaryAccountNumber'],
        'beneficiaryAccountName': json['beneficiaryAccountName'],
        'beneficiaryBankCode': json['beneficiaryBankCode'] == null ? undefined : json['beneficiaryBankCode'],
        'beneficiaryBankShortName': json['beneficiaryBankShortName'] == null ? undefined : json['beneficiaryBankShortName'],
        'beneficiaryBankName': json['beneficiaryBankName'] == null ? undefined : json['beneficiaryBankName'],
        'amount': MoneyFromJSON(json['amount']),
        'additionalInfo': json['additionalInfo'] == null ? undefined : BankAccountInquiryResponseAdditionalInfoFromJSON(json['additionalInfo']),
    };
}

export function BankAccountInquiryResponseToJSON(json: any): BankAccountInquiryResponse {
    return BankAccountInquiryResponseToJSONTyped(json, false);
}

export function BankAccountInquiryResponseToJSONTyped(value?: BankAccountInquiryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseCode': value['responseCode'],
        'responseMessage': value['responseMessage'],
        'referenceNo': value['referenceNo'],
        'partnerReferenceNo': value['partnerReferenceNo'],
        'accountType': value['accountType'],
        'beneficiaryAccountNumber': value['beneficiaryAccountNumber'],
        'beneficiaryAccountName': value['beneficiaryAccountName'],
        'beneficiaryBankCode': value['beneficiaryBankCode'],
        'beneficiaryBankShortName': value['beneficiaryBankShortName'],
        'beneficiaryBankName': value['beneficiaryBankName'],
        'amount': MoneyToJSON(value['amount']),
        'additionalInfo': BankAccountInquiryResponseAdditionalInfoToJSON(value['additionalInfo']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    responseCode: {
        maxLength: 7,
    },
    responseMessage: {
        maxLength: 150,
    },
    referenceNo: {
        maxLength: 64,
    },
    partnerReferenceNo: {
        maxLength: 64,
    },
    accountType: {
        maxLength: 25,
    },
    beneficiaryAccountNumber: {
        maxLength: 32,
    },
    beneficiaryAccountName: {
        maxLength: 64,
    },
    beneficiaryBankCode: {
        maxLength: 8,
    },
    beneficiaryBankShortName: {
        maxLength: 25,
    },
    beneficiaryBankName: {
        maxLength: 25,
    },
}

export function validateBankAccountInquiryResponse(value: BankAccountInquiryResponse): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseCode', value.responseCode, propertyValidationAttributesMap['responseCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseMessage', value.responseMessage, propertyValidationAttributesMap['responseMessage']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('referenceNo', value.referenceNo, propertyValidationAttributesMap['referenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('partnerReferenceNo', value.partnerReferenceNo, propertyValidationAttributesMap['partnerReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('accountType', value.accountType, propertyValidationAttributesMap['accountType']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryAccountNumber', value.beneficiaryAccountNumber, propertyValidationAttributesMap['beneficiaryAccountNumber']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryAccountName', value.beneficiaryAccountName, propertyValidationAttributesMap['beneficiaryAccountName']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryBankCode', value.beneficiaryBankCode, propertyValidationAttributesMap['beneficiaryBankCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryBankShortName', value.beneficiaryBankShortName, propertyValidationAttributesMap['beneficiaryBankShortName']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryBankName', value.beneficiaryBankName, propertyValidationAttributesMap['beneficiaryBankName']));

    validationErrorContexts.push(...validateMoney(value.amount));

    validationErrorContexts.push(...validateBankAccountInquiryResponseAdditionalInfo(value.additionalInfo));

    return validationErrorContexts;
}
