/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
/**
 * 
 * @export
 * @interface QueryMerchantResourceResponseResponseHead
 */
export interface QueryMerchantResourceResponseResponseHead {
    /**
     * API version
     * @type {string}
     * @memberof QueryMerchantResourceResponseResponseHead
     */
    version: string;
    /**
     * API interface
     * @type {string}
     * @memberof QueryMerchantResourceResponseResponseHead
     */
    _function: QueryMerchantResourceResponseResponseHeadFunctionEnum;
    /**
     * Client ID provided by DANA, used to identify partner and application system
     * @type {string}
     * @memberof QueryMerchantResourceResponseResponseHead
     */
    clientId: string;
    /**
     * DateTime with timezone, which follows the ISO-8601 standard. Refer to RFC 3339 Section 5.6
     * @type {Date}
     * @memberof QueryMerchantResourceResponseResponseHead
     */
    respTime: Date;
    /**
     * Request message ID
     * @type {string}
     * @memberof QueryMerchantResourceResponseResponseHead
     */
    reqMsgId: string;
}


/**
 * @export
 */
export const QueryMerchantResourceResponseResponseHeadFunctionEnum = {
    DanaMerchantQueryMerchantResource: 'dana.merchant.queryMerchantResource'
} as const;
export type QueryMerchantResourceResponseResponseHeadFunctionEnum = typeof QueryMerchantResourceResponseResponseHeadFunctionEnum[keyof typeof QueryMerchantResourceResponseResponseHeadFunctionEnum] | '';


/**
 * Check if a given object implements the QueryMerchantResourceResponseResponseHead interface.
 */
export function instanceOfQueryMerchantResourceResponseResponseHead(value: object): value is QueryMerchantResourceResponseResponseHead {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('respTime' in value) || value['respTime'] === undefined) return false;
    if (!('reqMsgId' in value) || value['reqMsgId'] === undefined) return false;
    return true;
}

export function QueryMerchantResourceResponseResponseHeadFromJSON(json: any): QueryMerchantResourceResponseResponseHead {
    return QueryMerchantResourceResponseResponseHeadFromJSONTyped(json, false);
}

export function QueryMerchantResourceResponseResponseHeadFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMerchantResourceResponseResponseHead {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        '_function': json['function'],
        'clientId': json['clientId'],
        'respTime': (new Date(json['respTime'])),
        'reqMsgId': json['reqMsgId'],
    };
}

export function QueryMerchantResourceResponseResponseHeadToJSON(json: any): QueryMerchantResourceResponseResponseHead {
    return QueryMerchantResourceResponseResponseHeadToJSONTyped(json, false);
}

export function QueryMerchantResourceResponseResponseHeadToJSONTyped(value?: QueryMerchantResourceResponseResponseHead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'function': value['_function'],
        'clientId': value['clientId'],
        'respTime': ((value['respTime']).toISOString()),
        'reqMsgId': value['reqMsgId'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    version: {
        maxLength: 8,
    },
    _function: {
        maxLength: 128,
    },
    clientId: {
        maxLength: 32,
    },
    reqMsgId: {
        maxLength: 64,
    },
}

export function validateQueryMerchantResourceResponseResponseHead(value: QueryMerchantResourceResponseResponseHead): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('version', value.version, propertyValidationAttributesMap['version']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('_function', value._function, propertyValidationAttributesMap['_function']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('clientId', value.clientId, propertyValidationAttributesMap['clientId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('reqMsgId', value.reqMsgId, propertyValidationAttributesMap['reqMsgId']));

    return validationErrorContexts;
}
