/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface TransferToDanaInquiryStatusResponse
 */
export interface TransferToDanaInquiryStatusResponse {
    /**
     * Refer to response code list
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    responseCode: string;
    /**
     * Refer to response code list
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    responseMessage: string;
    /**
     * Original transaction identifier on partner system
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    originalPartnerReferenceNo: string;
    /**
     * Original transaction identifier on DANA system
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    originalReferenceNo?: string;
    /**
     * Original external identifier on header message
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    originalExternalId?: string;
    /**
     * Transaction type indicator is based on the service code of the original transaction request, value always 38
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    serviceCode: string;
    /**
     * Amount. Contains two sub-fields:<br>
     * 1. Value: Transaction amount, including the cents<br>
     * 2. Currency: Currency code based on ISO
     * 
     * @type {Money}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    amount: Money;
    /**
     * Status of latest transaction:<br>
     * 00 - Success<br>
     * 01 - Initiated<br>
     * 02 - Paying<br>
     * 03 - Pending<br>
     * 04 - Refunded<br>
     * 05 - Cancelled<br>
     * 06 - Failed<br>
     * 07 - Not found
     * 
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    latestTransactionStatus: TransferToDanaInquiryStatusResponseLatestTransactionStatusEnum;
    /**
     * Description of transaction status
     * @type {string}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    transactionStatusDesc: string;
    /**
     * Additional information
     * @type {object}
     * @memberof TransferToDanaInquiryStatusResponse
     */
    additionalInfo?: object;
}


/**
 * @export
 */
export const TransferToDanaInquiryStatusResponseLatestTransactionStatusEnum = {
    _00: '00',
    _01: '01',
    _02: '02',
    _03: '03',
    _04: '04',
    _05: '05',
    _06: '06',
    _07: '07'
} as const;
export type TransferToDanaInquiryStatusResponseLatestTransactionStatusEnum = typeof TransferToDanaInquiryStatusResponseLatestTransactionStatusEnum[keyof typeof TransferToDanaInquiryStatusResponseLatestTransactionStatusEnum] | '';


/**
 * Check if a given object implements the TransferToDanaInquiryStatusResponse interface.
 */
export function instanceOfTransferToDanaInquiryStatusResponse(value: object): value is TransferToDanaInquiryStatusResponse {
    if (!('responseCode' in value) || value['responseCode'] === undefined) return false;
    if (!('responseMessage' in value) || value['responseMessage'] === undefined) return false;
    if (!('originalPartnerReferenceNo' in value) || value['originalPartnerReferenceNo'] === undefined) return false;
    if (!('serviceCode' in value) || value['serviceCode'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('latestTransactionStatus' in value) || value['latestTransactionStatus'] === undefined) return false;
    if (!('transactionStatusDesc' in value) || value['transactionStatusDesc'] === undefined) return false;
    return true;
}

export function TransferToDanaInquiryStatusResponseFromJSON(json: any): TransferToDanaInquiryStatusResponse {
    return TransferToDanaInquiryStatusResponseFromJSONTyped(json, false);
}

export function TransferToDanaInquiryStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferToDanaInquiryStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'responseCode': json['responseCode'],
        'responseMessage': json['responseMessage'],
        'originalPartnerReferenceNo': json['originalPartnerReferenceNo'],
        'originalReferenceNo': json['originalReferenceNo'] == null ? undefined : json['originalReferenceNo'],
        'originalExternalId': json['originalExternalId'] == null ? undefined : json['originalExternalId'],
        'serviceCode': json['serviceCode'],
        'amount': MoneyFromJSON(json['amount']),
        'latestTransactionStatus': json['latestTransactionStatus'],
        'transactionStatusDesc': json['transactionStatusDesc'],
        'additionalInfo': json['additionalInfo'] == null ? undefined : json['additionalInfo'],
    };
}

export function TransferToDanaInquiryStatusResponseToJSON(json: any): TransferToDanaInquiryStatusResponse {
    return TransferToDanaInquiryStatusResponseToJSONTyped(json, false);
}

export function TransferToDanaInquiryStatusResponseToJSONTyped(value?: TransferToDanaInquiryStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseCode': value['responseCode'],
        'responseMessage': value['responseMessage'],
        'originalPartnerReferenceNo': value['originalPartnerReferenceNo'],
        'originalReferenceNo': value['originalReferenceNo'],
        'originalExternalId': value['originalExternalId'],
        'serviceCode': value['serviceCode'],
        'amount': MoneyToJSON(value['amount']),
        'latestTransactionStatus': value['latestTransactionStatus'],
        'transactionStatusDesc': value['transactionStatusDesc'],
        'additionalInfo': value['additionalInfo'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    responseCode: {
        maxLength: 7,
    },
    responseMessage: {
        maxLength: 150,
    },
    originalPartnerReferenceNo: {
        maxLength: 64,
    },
    originalReferenceNo: {
        maxLength: 64,
    },
    originalExternalId: {
        maxLength: 36,
    },
    serviceCode: {
        maxLength: 2,
    },
    latestTransactionStatus: {
        maxLength: 2,
    },
    transactionStatusDesc: {
        maxLength: 50,
    },
}

export function validateTransferToDanaInquiryStatusResponse(value: TransferToDanaInquiryStatusResponse): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseCode', value.responseCode, propertyValidationAttributesMap['responseCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('responseMessage', value.responseMessage, propertyValidationAttributesMap['responseMessage']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalPartnerReferenceNo', value.originalPartnerReferenceNo, propertyValidationAttributesMap['originalPartnerReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalReferenceNo', value.originalReferenceNo, propertyValidationAttributesMap['originalReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalExternalId', value.originalExternalId, propertyValidationAttributesMap['originalExternalId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('serviceCode', value.serviceCode, propertyValidationAttributesMap['serviceCode']));

    validationErrorContexts.push(...validateMoney(value.amount));

    validationErrorContexts.push(...ValidationUtil.validateProperty('latestTransactionStatus', value.latestTransactionStatus, propertyValidationAttributesMap['latestTransactionStatus']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('transactionStatusDesc', value.transactionStatusDesc, propertyValidationAttributesMap['transactionStatusDesc']));

    return validationErrorContexts;
}
