/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
/**
 * Additional information
 * @export
 * @interface TransferToBankRequestAdditionalInfo
 */
export interface TransferToBankRequestAdditionalInfo {
    /**
     * Additional information of withdraw fund type, i.e.<br>
     * MERCHANT_WITHDRAW_FOR_CORPORATE
     * 
     * @type {string}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    fundType: string;
    /**
     * Additional information of external division identifier. (fundType: MERCHANT_WITHDRAW_FOR_CORPORATE)<br>
     * Notes: The required of this parameter is Optional, but if "additionalInfo.chargeTarget" has value DIVISION then the required of this parameter will be changed to Mandatory
     * 
     * @type {string}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    externalDivisionId?: string;
    /**
     * Additional information of charge target. The values are:<br>
     * • null<br>
     * • DIVISION<br>
     * • MERCHANT<br>
     * Notes: If the value is DIVISION, externalDivisionId will be Mandatory
     * 
     * @type {string}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    chargeTarget?: TransferToBankRequestAdditionalInfoChargeTargetEnum;
    /**
     * Additional information of flag result notification on transaction completed (result sync/async)
     * @type {boolean}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    needNotify?: boolean;
    /**
     * Additional information of beneficiary account name for validation purpose
     * @type {string}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    beneficiaryAccountName?: string;
    /**
     * Contains customer token, which has been obtained from binding process, refer to Account Binding & Unbinding documentation<br>
     * If request is coming from user interaction, this field is mandatory. If not, just filled customerNumber
     * 
     * @type {string}
     * @memberof TransferToBankRequestAdditionalInfo
     */
    accessToken?: string;
}


/**
 * @export
 */
export const TransferToBankRequestAdditionalInfoChargeTargetEnum = {
    Division: 'DIVISION',
    Merchant: 'MERCHANT'
} as const;
export type TransferToBankRequestAdditionalInfoChargeTargetEnum = typeof TransferToBankRequestAdditionalInfoChargeTargetEnum[keyof typeof TransferToBankRequestAdditionalInfoChargeTargetEnum];


/**
 * Check if a given object implements the TransferToBankRequestAdditionalInfo interface.
 */
export function instanceOfTransferToBankRequestAdditionalInfo(value: object): value is TransferToBankRequestAdditionalInfo {
    if (!('fundType' in value) || value['fundType'] === undefined) return false;
    return true;
}

export function TransferToBankRequestAdditionalInfoFromJSON(json: any): TransferToBankRequestAdditionalInfo {
    return TransferToBankRequestAdditionalInfoFromJSONTyped(json, false);
}

export function TransferToBankRequestAdditionalInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferToBankRequestAdditionalInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fundType': json['fundType'],
        'externalDivisionId': json['externalDivisionId'] == null ? undefined : json['externalDivisionId'],
        'chargeTarget': json['chargeTarget'] == null ? undefined : json['chargeTarget'],
        'needNotify': json['needNotify'] == null ? undefined : json['needNotify'],
        'beneficiaryAccountName': json['beneficiaryAccountName'] == null ? undefined : json['beneficiaryAccountName'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function TransferToBankRequestAdditionalInfoToJSON(json: any): TransferToBankRequestAdditionalInfo {
    return TransferToBankRequestAdditionalInfoToJSONTyped(json, false);
}

export function TransferToBankRequestAdditionalInfoToJSONTyped(value?: TransferToBankRequestAdditionalInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fundType': value['fundType'],
        'externalDivisionId': value['externalDivisionId'],
        'chargeTarget': value['chargeTarget'],
        'needNotify': value['needNotify'],
        'beneficiaryAccountName': value['beneficiaryAccountName'],
        'accessToken': value['accessToken'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    fundType: {
        maxLength: 64,
    },
    externalDivisionId: {
        maxLength: 64,
    },
    chargeTarget: {
        maxLength: 64,
    },
    beneficiaryAccountName: {
        maxLength: 64,
    },
    accessToken: {
        maxLength: 512,
    },
}

export function validateTransferToBankRequestAdditionalInfo(value: TransferToBankRequestAdditionalInfo): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('fundType', value.fundType, propertyValidationAttributesMap['fundType']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('externalDivisionId', value.externalDivisionId, propertyValidationAttributesMap['externalDivisionId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('chargeTarget', value.chargeTarget, propertyValidationAttributesMap['chargeTarget']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('beneficiaryAccountName', value.beneficiaryAccountName, propertyValidationAttributesMap['beneficiaryAccountName']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('accessToken', value.accessToken, propertyValidationAttributesMap['accessToken']));

    return validationErrorContexts;
}
