/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { CreateOrderByRedirectAdditionalInfo } from './CreateOrderByRedirectAdditionalInfo';
import {
    validateCreateOrderByRedirectAdditionalInfo,
    CreateOrderByRedirectAdditionalInfoFromJSON,
    CreateOrderByRedirectAdditionalInfoFromJSONTyped,
    CreateOrderByRedirectAdditionalInfoToJSON,
    CreateOrderByRedirectAdditionalInfoToJSONTyped,
} from './CreateOrderByRedirectAdditionalInfo';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { UrlParam } from './UrlParam';
import {
    validateUrlParam,
    UrlParamFromJSON,
    UrlParamFromJSONTyped,
    UrlParamToJSON,
    UrlParamToJSONTyped,
} from './UrlParam';

/**
 * 
 * @export
 * @interface CreateOrderByRedirectRequest
 */
export interface CreateOrderByRedirectRequest {
    /**
     * 
     * @type {CreateOrderByRedirectAdditionalInfo}
     * @memberof CreateOrderByRedirectRequest
     */
    additionalInfo?: CreateOrderByRedirectAdditionalInfo;
    /**
     * Transaction identifier on partner system
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    partnerReferenceNo: string;
    /**
     * Merchant identifier that is unique per each merchant
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    merchantId: string;
    /**
     * Information of sub merchant identifier
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    subMerchantId?: string;
    /**
     * 
     * @type {Money}
     * @memberof CreateOrderByRedirectRequest
     */
    amount: Money;
    /**
     * Store identifier to indicate to which store this payment belongs to
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    externalStoreId?: string;
    /**
     * The time when the payment will be automatically expired, in format YYYY-MM-DDTHH:mm:ss+07:00. Time must be in GMT+7 (Jakarta time)
     * 
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    validUpTo?: string;
    /**
     * Payment method(s) that cannot be used for this
     * @type {string}
     * @memberof CreateOrderByRedirectRequest
     */
    disabledPayMethods?: string;
    /**
     * Notify URL that DANA must send the payment notification to
     * @type {Array<UrlParam>}
     * @memberof CreateOrderByRedirectRequest
     */
    urlParams: Array<UrlParam>;
}

/**
 * Check if a given object implements the CreateOrderByRedirectRequest interface.
 */
export function instanceOfCreateOrderByRedirectRequest(value: object): value is CreateOrderByRedirectRequest {
    if (!('partnerReferenceNo' in value) || value['partnerReferenceNo'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('urlParams' in value) || value['urlParams'] === undefined) return false;
    return true;
}

export function CreateOrderByRedirectRequestFromJSON(json: any): CreateOrderByRedirectRequest {
    return CreateOrderByRedirectRequestFromJSONTyped(json, false);
}

export function CreateOrderByRedirectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderByRedirectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInfo': json['additionalInfo'] == null ? undefined : CreateOrderByRedirectAdditionalInfoFromJSON(json['additionalInfo']),
        'partnerReferenceNo': json['partnerReferenceNo'],
        'merchantId': json['merchantId'],
        'subMerchantId': json['subMerchantId'] == null ? undefined : json['subMerchantId'],
        'amount': MoneyFromJSON(json['amount']),
        'externalStoreId': json['externalStoreId'] == null ? undefined : json['externalStoreId'],
        'validUpTo': json['validUpTo'] == null ? undefined : json['validUpTo'],
        'disabledPayMethods': json['disabledPayMethods'] == null ? undefined : json['disabledPayMethods'],
        'urlParams': ((json['urlParams'] as Array<any>).map(UrlParamFromJSON)),
    };
}

export function CreateOrderByRedirectRequestToJSON(json: any): CreateOrderByRedirectRequest {
    return CreateOrderByRedirectRequestToJSONTyped(json, false);
}

export function CreateOrderByRedirectRequestToJSONTyped(value?: CreateOrderByRedirectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalInfo': CreateOrderByRedirectAdditionalInfoToJSON(value['additionalInfo']),
        'partnerReferenceNo': value['partnerReferenceNo'],
        'merchantId': value['merchantId'],
        'subMerchantId': value['subMerchantId'],
        'amount': MoneyToJSON(value['amount']),
        'externalStoreId': value['externalStoreId'],
        'validUpTo': value['validUpTo'],
        'disabledPayMethods': value['disabledPayMethods'],
        'urlParams': ((value['urlParams'] as Array<any>).map(UrlParamToJSON)),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    partnerReferenceNo: {
        maxLength: 64,
    },
    merchantId: {
        maxLength: 64,
    },
    subMerchantId: {
        maxLength: 32,
    },
    externalStoreId: {
        maxLength: 64,
    },
    validUpTo: {
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
    },
    disabledPayMethods: {
        maxLength: 64,
    },
}

export function validateCreateOrderByRedirectRequest(value: CreateOrderByRedirectRequest): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateCreateOrderByRedirectAdditionalInfo(value.additionalInfo));

    validationErrorContexts.push(...ValidationUtil.validateProperty('partnerReferenceNo', value.partnerReferenceNo, propertyValidationAttributesMap['partnerReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantId', value.merchantId, propertyValidationAttributesMap['merchantId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('subMerchantId', value.subMerchantId, propertyValidationAttributesMap['subMerchantId']));

    validationErrorContexts.push(...validateMoney(value.amount));

    validationErrorContexts.push(...ValidationUtil.validateProperty('externalStoreId', value.externalStoreId, propertyValidationAttributesMap['externalStoreId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('validUpTo', value.validUpTo, propertyValidationAttributesMap['validUpTo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('disabledPayMethods', value.disabledPayMethods, propertyValidationAttributesMap['disabledPayMethods']));

    return validationErrorContexts;
}
