/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface Goods
 */
export interface Goods {
    /**
     * Goods identifier provided by merchant
     * @type {string}
     * @memberof Goods
     */
    merchantGoodsId: string;
    /**
     * Goods description
     * @type {string}
     * @memberof Goods
     */
    description: string;
    /**
     * Goods category
     * @type {string}
     * @memberof Goods
     */
    category: string;
    /**
     * Goods price. Contains two sub-fields:<br>
     * 1. Value: Transaction amount, including the cents<br>
     * 2. Currency: Currency code based on ISO<br>
     * 
     * @type {Money}
     * @memberof Goods
     */
    price: Money;
    /**
     * Goods unit
     * @type {string}
     * @memberof Goods
     */
    unit?: string;
    /**
     * Count of items
     * @type {string}
     * @memberof Goods
     */
    quantity: string;
    /**
     * Shipment identifier provided by merchant
     * @type {string}
     * @memberof Goods
     */
    merchantShippingId?: string;
    /**
     * The URL of good's snapshot web page
     * @type {string}
     * @memberof Goods
     */
    snapshotUrl?: string;
    /**
     * Extend information
     * @type {string}
     * @memberof Goods
     */
    extendInfo?: string;
}

/**
 * Check if a given object implements the Goods interface.
 */
export function instanceOfGoods(value: object): value is Goods {
    if (!('merchantGoodsId' in value) || value['merchantGoodsId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function GoodsFromJSON(json: any): Goods {
    return GoodsFromJSONTyped(json, false);
}

export function GoodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Goods {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantGoodsId': json['merchantGoodsId'],
        'description': json['description'],
        'category': json['category'],
        'price': MoneyFromJSON(json['price']),
        'unit': json['unit'] == null ? undefined : json['unit'],
        'quantity': json['quantity'],
        'merchantShippingId': json['merchantShippingId'] == null ? undefined : json['merchantShippingId'],
        'snapshotUrl': json['snapshotUrl'] == null ? undefined : json['snapshotUrl'],
        'extendInfo': json['extendInfo'] == null ? undefined : json['extendInfo'],
    };
}

export function GoodsToJSON(json: any): Goods {
    return GoodsToJSONTyped(json, false);
}

export function GoodsToJSONTyped(value?: Goods | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantGoodsId': value['merchantGoodsId'],
        'description': value['description'],
        'category': value['category'],
        'price': MoneyToJSON(value['price']),
        'unit': value['unit'],
        'quantity': value['quantity'],
        'merchantShippingId': value['merchantShippingId'],
        'snapshotUrl': value['snapshotUrl'],
        'extendInfo': value['extendInfo'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    merchantGoodsId: {
        maxLength: 64,
    },
    description: {
        maxLength: 1024,
    },
    category: {
        maxLength: 64,
    },
    unit: {
        maxLength: 64,
    },
    quantity: {
        maxLength: 16,
    },
    merchantShippingId: {
        maxLength: 64,
    },
    snapshotUrl: {
        maxLength: 512,
    },
    extendInfo: {
        maxLength: 4096,
    },
}

export function validateGoods(value: Goods): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantGoodsId', value.merchantGoodsId, propertyValidationAttributesMap['merchantGoodsId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('description', value.description, propertyValidationAttributesMap['description']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('category', value.category, propertyValidationAttributesMap['category']));

    validationErrorContexts.push(...validateMoney(value.price));

    validationErrorContexts.push(...ValidationUtil.validateProperty('unit', value.unit, propertyValidationAttributesMap['unit']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('quantity', value.quantity, propertyValidationAttributesMap['quantity']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantShippingId', value.merchantShippingId, propertyValidationAttributesMap['merchantShippingId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('snapshotUrl', value.snapshotUrl, propertyValidationAttributesMap['snapshotUrl']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('extendInfo', value.extendInfo, propertyValidationAttributesMap['extendInfo']));

    return validationErrorContexts;
}
