/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import { validateValidUpToDate } from '../../../utils/DateValidation';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { UrlParam } from './UrlParam';
import {
    validateUrlParam,
    UrlParamFromJSON,
    UrlParamFromJSONTyped,
    UrlParamToJSON,
    UrlParamToJSONTyped,
} from './UrlParam';
import type { WidgetPaymentRequestAdditionalInfo } from './WidgetPaymentRequestAdditionalInfo';
import {
    validateWidgetPaymentRequestAdditionalInfo,
    WidgetPaymentRequestAdditionalInfoFromJSON,
    WidgetPaymentRequestAdditionalInfoFromJSONTyped,
    WidgetPaymentRequestAdditionalInfoToJSON,
    WidgetPaymentRequestAdditionalInfoToJSONTyped,
} from './WidgetPaymentRequestAdditionalInfo';
import type { PayOptionDetail } from './PayOptionDetail';
import {
    validatePayOptionDetail,
    PayOptionDetailFromJSON,
    PayOptionDetailFromJSONTyped,
    PayOptionDetailToJSON,
    PayOptionDetailToJSONTyped,
} from './PayOptionDetail';

/**
 * 
 * @export
 * @interface WidgetPaymentRequest
 */
export interface WidgetPaymentRequest {
    /**
     * Unique transaction identifier on partner system which assigned to each transaction
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    partnerReferenceNo: string;
    /**
     * Merchant identifier that is unique per each merchant
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    subMerchantId?: string;
    /**
     * 
     * @type {Money}
     * @memberof WidgetPaymentRequest
     */
    amount: Money;
    /**
     * Store identifier to indicate to which store this payment belongs to
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    externalStoreId?: string;
    /**
     * The time when the payment will be automatically expired, in format YYYY-MM-DDTHH:mm:ss+07:00. Time must be in GMT+7 (Jakarta time)
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    validUpTo: string;
    /**
     * Used for getting more info regarding source of request of the user
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    pointOfInitiation?: string;
    /**
     * Payment method(s) that cannot be used for this payment
     * @type {string}
     * @memberof WidgetPaymentRequest
     */
    disabledPayMethods?: string;
    /**
     * Payment option that will be used for this payment
     * @type {Array<PayOptionDetail>}
     * @memberof WidgetPaymentRequest
     */
    payOptionDetails?: Array<PayOptionDetail>;
    /**
     * 
     * @type {WidgetPaymentRequestAdditionalInfo}
     * @memberof WidgetPaymentRequest
     */
    additionalInfo: WidgetPaymentRequestAdditionalInfo;
    /**
     * Notify URL that DANA must send the payment notification to
     * @type {Array<UrlParam>}
     * @memberof WidgetPaymentRequest
     */
    urlParams?: Array<UrlParam>;
}

/**
 * Check if a given object implements the WidgetPaymentRequest interface.
 */
export function instanceOfWidgetPaymentRequest(value: object): value is WidgetPaymentRequest {
    if (!('partnerReferenceNo' in value) || value['partnerReferenceNo'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('validUpTo' in value) || value['validUpTo'] === undefined) return false;
    if (!('additionalInfo' in value) || value['additionalInfo'] === undefined) return false;
    return true;
}

export function WidgetPaymentRequestFromJSON(json: any): WidgetPaymentRequest {
    return WidgetPaymentRequestFromJSONTyped(json, false);
}

export function WidgetPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'partnerReferenceNo': json['partnerReferenceNo'],
        'merchantId': json['merchantId'],
        'subMerchantId': json['subMerchantId'] == null ? undefined : json['subMerchantId'],
        'amount': MoneyFromJSON(json['amount']),
        'externalStoreId': json['externalStoreId'] == null ? undefined : json['externalStoreId'],
        'validUpTo': json['validUpTo'],
        'pointOfInitiation': json['pointOfInitiation'] == null ? undefined : json['pointOfInitiation'],
        'disabledPayMethods': json['disabledPayMethods'] == null ? undefined : json['disabledPayMethods'],
        'payOptionDetails': json['payOptionDetails'] == null ? undefined : ((json['payOptionDetails'] as Array<any>).map(PayOptionDetailFromJSON)),
        'additionalInfo': WidgetPaymentRequestAdditionalInfoFromJSON(json['additionalInfo']),
        'urlParams': json['urlParams'] == null ? undefined : ((json['urlParams'] as Array<any>).map(UrlParamFromJSON)),
    };
}

export function WidgetPaymentRequestToJSON(json: any): WidgetPaymentRequest {
    return WidgetPaymentRequestToJSONTyped(json, false);
}

export function WidgetPaymentRequestToJSONTyped(value?: WidgetPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'partnerReferenceNo': value['partnerReferenceNo'],
        'merchantId': value['merchantId'],
        'subMerchantId': value['subMerchantId'],
        'amount': MoneyToJSON(value['amount']),
        'externalStoreId': value['externalStoreId'],
        'validUpTo': value['validUpTo'],
        'pointOfInitiation': value['pointOfInitiation'],
        'disabledPayMethods': value['disabledPayMethods'],
        'payOptionDetails': value['payOptionDetails'] == null ? undefined : ((value['payOptionDetails'] as Array<any>).map(PayOptionDetailToJSON)),
        'additionalInfo': WidgetPaymentRequestAdditionalInfoToJSON(value['additionalInfo']),
        'urlParams': value['urlParams'] == null ? undefined : ((value['urlParams'] as Array<any>).map(UrlParamToJSON)),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    partnerReferenceNo: {
        maxLength: 64,
    },
    merchantId: {
        maxLength: 64,
    },
    subMerchantId: {
        maxLength: 32,
    },
    externalStoreId: {
        maxLength: 64,
    },
    validUpTo: {
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
        maxDate: "week",
    },
    pointOfInitiation: {
        maxLength: 20,
    },
    disabledPayMethods: {
        maxLength: 64,
    },
}

export function validateWidgetPaymentRequest(value: WidgetPaymentRequest): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('partnerReferenceNo', value.partnerReferenceNo, propertyValidationAttributesMap['partnerReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantId', value.merchantId, propertyValidationAttributesMap['merchantId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('subMerchantId', value.subMerchantId, propertyValidationAttributesMap['subMerchantId']));

    validationErrorContexts.push(...validateMoney(value.amount));

    validationErrorContexts.push(...ValidationUtil.validateProperty('externalStoreId', value.externalStoreId, propertyValidationAttributesMap['externalStoreId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('validUpTo', value.validUpTo, propertyValidationAttributesMap['validUpTo']));

    // Validate that validUpTo date is not more than 30 minutes in the future (sandbox only)
    if (value.validUpTo != null) {
        try {
            validateValidUpToDate(value.validUpTo);
        } catch (error: any) {
            validationErrorContexts.push({
                field: 'validUpTo',
                message: 'validUpTo validation failed: ' + (error?.message || String(error))
            });
        }
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('pointOfInitiation', value.pointOfInitiation, propertyValidationAttributesMap['pointOfInitiation']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('disabledPayMethods', value.disabledPayMethods, propertyValidationAttributesMap['disabledPayMethods']));

    validationErrorContexts.push(...validateWidgetPaymentRequestAdditionalInfo(value.additionalInfo));

    return validationErrorContexts;
}
