/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import * as runtime from '../../../runtime';
import type {
  AccountUnbindingRequest,
  AccountUnbindingResponse,
  ApplyOTTRequest,
  ApplyOTTResponse,
  ApplyTokenRequest,
  ApplyTokenResponse,
  CancelOrderRequest,
  CancelOrderResponse,
  IPGPaymentRequest,
  IPGPaymentResponse,
  QueryPaymentRequest,
  QueryPaymentResponse,
  RefundOrderRequest,
  RefundOrderResponse,
} from '../models/index';
import {
    validateAccountUnbindingRequest,
    AccountUnbindingRequestFromJSON,
    AccountUnbindingRequestToJSON,
    validateAccountUnbindingResponse,
    AccountUnbindingResponseFromJSON,
    AccountUnbindingResponseToJSON,
    validateApplyOTTRequest,
    ApplyOTTRequestFromJSON,
    ApplyOTTRequestToJSON,
    validateApplyOTTResponse,
    ApplyOTTResponseFromJSON,
    ApplyOTTResponseToJSON,
    validateApplyTokenRequest,
    ApplyTokenRequestFromJSON,
    ApplyTokenRequestToJSON,
    validateApplyTokenResponse,
    ApplyTokenResponseFromJSON,
    ApplyTokenResponseToJSON,
    validateCancelOrderRequest,
    CancelOrderRequestFromJSON,
    CancelOrderRequestToJSON,
    validateCancelOrderResponse,
    CancelOrderResponseFromJSON,
    CancelOrderResponseToJSON,
    validateIPGPaymentRequest,
    IPGPaymentRequestFromJSON,
    IPGPaymentRequestToJSON,
    validateIPGPaymentResponse,
    IPGPaymentResponseFromJSON,
    IPGPaymentResponseToJSON,
    validateQueryPaymentRequest,
    QueryPaymentRequestFromJSON,
    QueryPaymentRequestToJSON,
    validateQueryPaymentResponse,
    QueryPaymentResponseFromJSON,
    QueryPaymentResponseToJSON,
    validateRefundOrderRequest,
    RefundOrderRequestFromJSON,
    RefundOrderRequestToJSON,
    validateRefundOrderResponse,
    RefundOrderResponseFromJSON,
    RefundOrderResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class IPGApi extends runtime.BaseAPI {

    partnerId: string = "";
    privateKey: string = "";
    origin: string = "";
    env: string = "";

    constructor({ partnerId, privateKey, origin, env }: { partnerId?: string, privateKey?: string, origin?: string, env?: string }) {
        const basePath = runtime.getBasePathByEnv(env);

        const configuration = new runtime.Configuration({
            basePath: basePath,
        })

        super(configuration);

        this.partnerId = partnerId;
        this.privateKey = privateKey;
        this.origin = origin;
        this.env = env;
    }

    /**
     * This API is used to reverses the account binding process by revoking the accessToken and refreshToken
     * Account unbinding - Binding
     */
    async accountUnbinding(accountUnbindingRequest: AccountUnbindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountUnbindingResponse> {
        if (accountUnbindingRequest == null) {
            throw new runtime.RequiredError(
                'accountUnbindingRequest',
                'Required parameter "accountUnbindingRequest" was null or undefined when calling accountUnbinding().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateAccountUnbindingRequest(accountUnbindingRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/v1.0/registration-account-unbinding.htm`;

        const requestBody: string = JSON.stringify(AccountUnbindingRequestToJSON(accountUnbindingRequest));
        
        const accessToken = accountUnbindingRequest.additionalInfo.accessToken;
        const endUserIpAddress = accountUnbindingRequest.additionalInfo.endUserIpAddress;
        const deviceId = accountUnbindingRequest.additionalInfo.deviceId;
        const latitude = accountUnbindingRequest.additionalInfo.latitude;
        const longitude = accountUnbindingRequest.additionalInfo.longitude;

        runtime.DanaHeaderUtil.populateSnapAccountB2B2CScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId, accessToken, endUserIpAddress, deviceId, latitude, longitude);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountUnbindingRequestToJSON(accountUnbindingRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountUnbindingResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to get one time token that will be used as authorization parameter upon redirecting to DANA
     * Apply OTT - IPG
     */
    async applyOTT(applyOTTRequest: ApplyOTTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyOTTResponse> {
        if (applyOTTRequest == null) {
            throw new runtime.RequiredError(
                'applyOTTRequest',
                'Required parameter "applyOTTRequest" was null or undefined when calling applyOTT().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateApplyOTTRequest(applyOTTRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/rest/v1.1/qr/apply-ott`;

        const requestBody: string = JSON.stringify(ApplyOTTRequestToJSON(applyOTTRequest));
        
        const accessToken = applyOTTRequest.additionalInfo.accessToken;
        const endUserIpAddress = applyOTTRequest.additionalInfo.endUserIpAddress;
        const deviceId = applyOTTRequest.additionalInfo.deviceId;
        const latitude = applyOTTRequest.additionalInfo.latitude;
        const longitude = applyOTTRequest.additionalInfo.longitude;

        runtime.DanaHeaderUtil.populateSnapAccountB2B2CScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId, accessToken, endUserIpAddress, deviceId, latitude, longitude);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplyOTTRequestToJSON(applyOTTRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplyOTTResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to finalized account binding process by exchanging the authCode into accessToken that can be used as user authorization
     * Apply Token, required by Apply OTT - Binding
     */
    async applyToken(applyTokenRequest: ApplyTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplyTokenResponse> {
        if (applyTokenRequest == null) {
            throw new runtime.RequiredError(
                'applyTokenRequest',
                'Required parameter "applyTokenRequest" was null or undefined when calling applyToken().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateApplyTokenRequest(applyTokenRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/v1.0/access-token/b2b2c.htm`;

        runtime.DanaHeaderUtil.populateSnapApplyTokenScenarioHeader(headerParameters, this.privateKey, this.partnerId);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplyTokenRequestToJSON(applyTokenRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplyTokenResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to cancel the order from merchant\'s platform to DANA
     * Cancel Order - IPG
     */
    async cancelOrder(cancelOrderRequest: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CancelOrderResponse> {
        if (cancelOrderRequest == null) {
            throw new runtime.RequiredError(
                'cancelOrderRequest',
                'Required parameter "cancelOrderRequest" was null or undefined when calling cancelOrder().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateCancelOrderRequest(cancelOrderRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/v1.0/debit/cancel.htm`;

        const requestBody: string = JSON.stringify(CancelOrderRequestToJSON(cancelOrderRequest));

        runtime.DanaHeaderUtil.populateSnapB2BScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelOrderRequestToJSON(cancelOrderRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CancelOrderResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to initiate payment from merchant\'s platform to DANA
     * IPG payment - IPG
     */
    async ipgPayment(iPGPaymentRequest: IPGPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IPGPaymentResponse> {
        if (iPGPaymentRequest == null) {
            throw new runtime.RequiredError(
                'iPGPaymentRequest',
                'Required parameter "iPGPaymentRequest" was null or undefined when calling ipgPayment().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateIPGPaymentRequest(iPGPaymentRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/rest/redirection/v1.0/debit/payment-host-to-host`;

        const requestBody: string = JSON.stringify(IPGPaymentRequestToJSON(iPGPaymentRequest));

        runtime.DanaHeaderUtil.populateSnapB2BScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IPGPaymentRequestToJSON(iPGPaymentRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IPGPaymentResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to inquiry payment status and information from merchant\'s platform to DANA
     * Query Payment - IPG
     */
    async queryPayment(queryPaymentRequest: QueryPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryPaymentResponse> {
        if (queryPaymentRequest == null) {
            throw new runtime.RequiredError(
                'queryPaymentRequest',
                'Required parameter "queryPaymentRequest" was null or undefined when calling queryPayment().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateQueryPaymentRequest(queryPaymentRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/rest/v1.1/debit/status`;

        const requestBody: string = JSON.stringify(QueryPaymentRequestToJSON(queryPaymentRequest));

        runtime.DanaHeaderUtil.populateSnapB2BScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryPaymentRequestToJSON(queryPaymentRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryPaymentResponseFromJSON(jsonValue)).value();
    }

    /**
     * This API is used to refund the order from merchant\'s platform to DANA
     * Refund Order - IPG
     */
    async refundOrder(refundOrderRequest: RefundOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundOrderResponse> {
        if (refundOrderRequest == null) {
            throw new runtime.RequiredError(
                'refundOrderRequest',
                'Required parameter "refundOrderRequest" was null or undefined when calling refundOrder().'
            );
        }

        const validationErrorContexts: runtime.ValidationErrorContext[] = validateRefundOrderRequest(refundOrderRequest);
        if (validationErrorContexts.length > 0) {
            throw new runtime.ValidationError(validationErrorContexts);
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const endpointUrl: string = `/v1.0/debit/refund.htm`;

        const requestBody: string = JSON.stringify(RefundOrderRequestToJSON(refundOrderRequest));

        runtime.DanaHeaderUtil.populateSnapB2BScenarioHeader(headerParameters, 'POST', endpointUrl, requestBody, this.privateKey, this.origin, this.partnerId);

        const response = await this.request({
            path: endpointUrl,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefundOrderRequestToJSON(refundOrderRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundOrderResponseFromJSON(jsonValue)).value();
    }

}
