/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../runtime';
import { mapValues, ValidationUtil } from '../../runtime';
import type { Money } from './Money';
import {
    validateMoney,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { FinishNotifyRequestAdditionalInfo } from './FinishNotifyRequestAdditionalInfo';
import {
    validateFinishNotifyRequestAdditionalInfo,
    FinishNotifyRequestAdditionalInfoFromJSON,
    FinishNotifyRequestAdditionalInfoFromJSONTyped,
    FinishNotifyRequestAdditionalInfoToJSON,
    FinishNotifyRequestAdditionalInfoToJSONTyped,
} from './FinishNotifyRequestAdditionalInfo';

/**
 * 
 * @export
 * @interface FinishNotifyRequest
 */
export interface FinishNotifyRequest {
    /**
     * Original transaction identifier on DANA system
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    originalPartnerReferenceNo: string;
    /**
     * Original transaction identifier on partner system
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    originalReferenceNo: string;
    /**
     * Original external identifier on header message
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    originalExternalId?: string;
    /**
     * Unique identifier per each merchant
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    merchantId: string;
    /**
     * Information of sub merchant identifier
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    subMerchantId?: string;
    /**
     * Amount. Contains two sub-fields:<br>
     * 1. Value: Transaction amount, including the cents<br>
     * 2. Currency: Currency code based on ISO<br>
     * 
     * @type {Money}
     * @memberof FinishNotifyRequest
     */
    amount: Money;
    /**
     * Transaction status code:<br>
     * - 00 = Success, the order has been paid<br>
     * - 05 = Cancelled, the order has been closed because it is expired<br>
     * 
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    latestTransactionStatus: string;
    /**
     * Description of transaction status
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    transactionStatusDesc?: string;
    /**
     * Transaction created time, in format YYYY-MM-DDTHH:mm:ss+07:00. Time must be in GMT+7 (Jakarta time)
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    createdTime: string;
    /**
     * Transaction finished time, in format YYYY-MM-DDTHH:mm:ss+07:00. Time must be in GMT+7 (Jakarta time)
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    finishedTime: string;
    /**
     * Store identifier to indicate to which store this payment belongs to
     * @type {string}
     * @memberof FinishNotifyRequest
     */
    externalStoreId?: string;
    /**
     * Additional information
     * @type {FinishNotifyRequestAdditionalInfo}
     * @memberof FinishNotifyRequest
     */
    additionalInfo?: FinishNotifyRequestAdditionalInfo;
}

/**
 * Check if a given object implements the FinishNotifyRequest interface.
 */
export function instanceOfFinishNotifyRequest(value: object): value is FinishNotifyRequest {
    if (!('originalPartnerReferenceNo' in value) || value['originalPartnerReferenceNo'] === undefined) return false;
    if (!('originalReferenceNo' in value) || value['originalReferenceNo'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('latestTransactionStatus' in value) || value['latestTransactionStatus'] === undefined) return false;
    if (!('createdTime' in value) || value['createdTime'] === undefined) return false;
    if (!('finishedTime' in value) || value['finishedTime'] === undefined) return false;
    return true;
}

export function FinishNotifyRequestFromJSON(json: any): FinishNotifyRequest {
    return FinishNotifyRequestFromJSONTyped(json, false);
}

export function FinishNotifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishNotifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'originalPartnerReferenceNo': json['originalPartnerReferenceNo'],
        'originalReferenceNo': json['originalReferenceNo'],
        'originalExternalId': json['originalExternalId'] == null ? undefined : json['originalExternalId'],
        'merchantId': json['merchantId'],
        'subMerchantId': json['subMerchantId'] == null ? undefined : json['subMerchantId'],
        'amount': MoneyFromJSON(json['amount']),
        'latestTransactionStatus': json['latestTransactionStatus'],
        'transactionStatusDesc': json['transactionStatusDesc'] == null ? undefined : json['transactionStatusDesc'],
        'createdTime': json['createdTime'],
        'finishedTime': json['finishedTime'],
        'externalStoreId': json['externalStoreId'] == null ? undefined : json['externalStoreId'],
        'additionalInfo': json['additionalInfo'] == null ? undefined : FinishNotifyRequestAdditionalInfoFromJSON(json['additionalInfo']),
    };
}

export function FinishNotifyRequestToJSON(json: any): FinishNotifyRequest {
    return FinishNotifyRequestToJSONTyped(json, false);
}

export function FinishNotifyRequestToJSONTyped(value?: FinishNotifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'originalPartnerReferenceNo': value['originalPartnerReferenceNo'],
        'originalReferenceNo': value['originalReferenceNo'],
        'originalExternalId': value['originalExternalId'],
        'merchantId': value['merchantId'],
        'subMerchantId': value['subMerchantId'],
        'amount': MoneyToJSON(value['amount']),
        'latestTransactionStatus': value['latestTransactionStatus'],
        'transactionStatusDesc': value['transactionStatusDesc'],
        'createdTime': value['createdTime'],
        'finishedTime': value['finishedTime'],
        'externalStoreId': value['externalStoreId'],
        'additionalInfo': FinishNotifyRequestAdditionalInfoToJSON(value['additionalInfo']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    originalPartnerReferenceNo: {
        maxLength: 64,
    },
    originalReferenceNo: {
        maxLength: 64,
    },
    originalExternalId: {
        maxLength: 36,
    },
    merchantId: {
        maxLength: 64,
    },
    subMerchantId: {
        maxLength: 32,
    },
    latestTransactionStatus: {
        maxLength: 2,
    },
    transactionStatusDesc: {
        maxLength: 50,
    },
    createdTime: {
        maxLength: 25,
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
    },
    finishedTime: {
        maxLength: 25,
        pattern: new RegExp('/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+07:00$/'.slice(1, -1)),
    },
    externalStoreId: {
        maxLength: 64,
    },
}

export function validateFinishNotifyRequest(value: FinishNotifyRequest): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalPartnerReferenceNo', value.originalPartnerReferenceNo, propertyValidationAttributesMap['originalPartnerReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalReferenceNo', value.originalReferenceNo, propertyValidationAttributesMap['originalReferenceNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('originalExternalId', value.originalExternalId, propertyValidationAttributesMap['originalExternalId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantId', value.merchantId, propertyValidationAttributesMap['merchantId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('subMerchantId', value.subMerchantId, propertyValidationAttributesMap['subMerchantId']));

    validationErrorContexts.push(...validateMoney(value.amount));

    validationErrorContexts.push(...ValidationUtil.validateProperty('latestTransactionStatus', value.latestTransactionStatus, propertyValidationAttributesMap['latestTransactionStatus']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('transactionStatusDesc', value.transactionStatusDesc, propertyValidationAttributesMap['transactionStatusDesc']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('createdTime', value.createdTime, propertyValidationAttributesMap['createdTime']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('finishedTime', value.finishedTime, propertyValidationAttributesMap['finishedTime']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('externalStoreId', value.externalStoreId, propertyValidationAttributesMap['externalStoreId']));

    validationErrorContexts.push(...validateFinishNotifyRequestAdditionalInfo(value.additionalInfo));

    return validationErrorContexts;
}
