/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { ResultInfo } from './ResultInfo';
import {
    validateResultInfo,
    ResultInfoFromJSON,
    ResultInfoFromJSONTyped,
    ResultInfoToJSON,
    ResultInfoToJSONTyped,
} from './ResultInfo';

/**
 * 
 * @export
 * @interface CreateShopResponseResponseBody
 */
export interface CreateShopResponseResponseBody {
    /**
     * 
     * @type {ResultInfo}
     * @memberof CreateShopResponseResponseBody
     */
    resultInfo: ResultInfo;
    /**
     * The shop ID that was created. Present when resultCodeId is 00000000
     * @type {string}
     * @memberof CreateShopResponseResponseBody
     */
    shopId?: string;
}

/**
 * Check if a given object implements the CreateShopResponseResponseBody interface.
 */
export function instanceOfCreateShopResponseResponseBody(value: object): value is CreateShopResponseResponseBody {
    if (!('resultInfo' in value) || value['resultInfo'] === undefined) return false;
    return true;
}

export function CreateShopResponseResponseBodyFromJSON(json: any): CreateShopResponseResponseBody {
    return CreateShopResponseResponseBodyFromJSONTyped(json, false);
}

export function CreateShopResponseResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShopResponseResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'resultInfo': ResultInfoFromJSON(json['resultInfo']),
        'shopId': json['shopId'] == null ? undefined : json['shopId'],
    };
}

export function CreateShopResponseResponseBodyToJSON(json: any): CreateShopResponseResponseBody {
    return CreateShopResponseResponseBodyToJSONTyped(json, false);
}

export function CreateShopResponseResponseBodyToJSONTyped(value?: CreateShopResponseResponseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultInfo': ResultInfoToJSON(value['resultInfo']),
        'shopId': value['shopId'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
}

export function validateCreateShopResponseResponseBody(value: CreateShopResponseResponseBody): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateResultInfo(value.resultInfo));

    return validationErrorContexts;
}
