/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
/**
 * Result information for member asset Open APIs (`resultInfo` per DANA spec)
 * @export
 * @interface MemberAssetResultInfo
 */
export interface MemberAssetResultInfo {
    /**
     * Request status (`ResultStatus`). S=Success, F=Failure, U=Unknown
     * @type {string}
     * @memberof MemberAssetResultInfo
     */
    resultStatus: MemberAssetResultInfoResultStatusEnum;
    /**
     * Result code identifier (`ResultCodeId`)
     * @type {string}
     * @memberof MemberAssetResultInfo
     */
    resultCodeId: string;
    /**
     * Result code (`ResultCode`)
     * @type {string}
     * @memberof MemberAssetResultInfo
     */
    resultCode: string;
    /**
     * Result message (`ResultMsg`). Optional per API contract
     * @type {string}
     * @memberof MemberAssetResultInfo
     */
    resultMsg?: string;
}


/**
 * @export
 */
export const MemberAssetResultInfoResultStatusEnum = {
    S: 'S',
    F: 'F',
    U: 'U'
} as const;
export type MemberAssetResultInfoResultStatusEnum = typeof MemberAssetResultInfoResultStatusEnum[keyof typeof MemberAssetResultInfoResultStatusEnum] | '';


/**
 * Check if a given object implements the MemberAssetResultInfo interface.
 */
export function instanceOfMemberAssetResultInfo(value: object): value is MemberAssetResultInfo {
    if (!('resultStatus' in value) || value['resultStatus'] === undefined) return false;
    if (!('resultCodeId' in value) || value['resultCodeId'] === undefined) return false;
    if (!('resultCode' in value) || value['resultCode'] === undefined) return false;
    return true;
}

export function MemberAssetResultInfoFromJSON(json: any): MemberAssetResultInfo {
    return MemberAssetResultInfoFromJSONTyped(json, false);
}

export function MemberAssetResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAssetResultInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'resultStatus': json['resultStatus'],
        'resultCodeId': json['resultCodeId'],
        'resultCode': json['resultCode'],
        'resultMsg': json['resultMsg'] == null ? undefined : json['resultMsg'],
    };
}

export function MemberAssetResultInfoToJSON(json: any): MemberAssetResultInfo {
    return MemberAssetResultInfoToJSONTyped(json, false);
}

export function MemberAssetResultInfoToJSONTyped(value?: MemberAssetResultInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultStatus': value['resultStatus'],
        'resultCodeId': value['resultCodeId'],
        'resultCode': value['resultCode'],
        'resultMsg': value['resultMsg'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    resultStatus: {
        maxLength: 1,
    },
    resultCodeId: {
        maxLength: 16,
    },
    resultCode: {
        maxLength: 64,
    },
    resultMsg: {
        maxLength: 256,
    },
}

export function validateMemberAssetResultInfo(value: MemberAssetResultInfo): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('resultStatus', value.resultStatus, propertyValidationAttributesMap['resultStatus']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('resultCodeId', value.resultCodeId, propertyValidationAttributesMap['resultCodeId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('resultCode', value.resultCode, propertyValidationAttributesMap['resultCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('resultMsg', value.resultMsg, propertyValidationAttributesMap['resultMsg']));

    return validationErrorContexts;
}
