/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { UserName } from './UserName';
import {
    validateUserName,
    UserNameFromJSON,
    UserNameFromJSONTyped,
    UserNameToJSON,
    UserNameToJSONTyped,
} from './UserName';
import type { MerchantContactEmail } from './MerchantContactEmail';
import {
    validateMerchantContactEmail,
    MerchantContactEmailFromJSON,
    MerchantContactEmailFromJSONTyped,
    MerchantContactEmailToJSON,
    MerchantContactEmailToJSONTyped,
} from './MerchantContactEmail';
import type { MerchantContactMobileNo } from './MerchantContactMobileNo';
import {
    validateMerchantContactMobileNo,
    MerchantContactMobileNoFromJSON,
    MerchantContactMobileNoFromJSONTyped,
    MerchantContactMobileNoToJSON,
    MerchantContactMobileNoToJSONTyped,
} from './MerchantContactMobileNo';
import type { MerchantContactAddress } from './MerchantContactAddress';
import {
    validateMerchantContactAddress,
    MerchantContactAddressFromJSON,
    MerchantContactAddressFromJSONTyped,
    MerchantContactAddressToJSON,
    MerchantContactAddressToJSONTyped,
} from './MerchantContactAddress';
import type { MerchantAccountInfo } from './MerchantAccountInfo';
import {
    validateMerchantAccountInfo,
    MerchantAccountInfoFromJSON,
    MerchantAccountInfoFromJSONTyped,
    MerchantAccountInfoToJSON,
    MerchantAccountInfoToJSONTyped,
} from './MerchantAccountInfo';
import type { MerchantCorporateCertificate } from './MerchantCorporateCertificate';
import {
    validateMerchantCorporateCertificate,
    MerchantCorporateCertificateFromJSON,
    MerchantCorporateCertificateFromJSONTyped,
    MerchantCorporateCertificateToJSON,
    MerchantCorporateCertificateToJSONTyped,
} from './MerchantCorporateCertificate';
import type { MerchantCertificateInfo } from './MerchantCertificateInfo';
import {
    validateMerchantCertificateInfo,
    MerchantCertificateInfoFromJSON,
    MerchantCertificateInfoFromJSONTyped,
    MerchantCertificateInfoToJSON,
    MerchantCertificateInfoToJSONTyped,
} from './MerchantCertificateInfo';

/**
 * Merchant profile detail (`merchantInformation` in response body)
 * @export
 * @interface MerchantInformation
 */
export interface MerchantInformation {
    /**
     * Phone number
     * @type {string}
     * @memberof MerchantInformation
     */
    phoneNumber?: string;
    /**
     * Merchant identifier
     * @type {string}
     * @memberof MerchantInformation
     */
    merchantId?: string;
    /**
     * Merchant type
     * @type {string}
     * @memberof MerchantInformation
     */
    merchantType?: MerchantInformationMerchantTypeEnum;
    /**
     * Merchant sub type
     * @type {string}
     * @memberof MerchantInformation
     */
    merchantSubType?: MerchantInformationMerchantSubTypeEnum;
    /**
     * Merchant category codes (MCC)
     * @type {Array<string>}
     * @memberof MerchantInformation
     */
    mccCodes?: Array<string>;
    /**
     * Logo URL
     * @type {string}
     * @memberof MerchantInformation
     */
    logoUrl?: string;
    /**
     * Logo map. Keys may be `LOGO`, `PC_LOGO`, `MOBILE_LOGO`.
     * Values are base64-encoded PNG image data.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MerchantInformation
     */
    logoUrlMap?: { [key: string]: string; };
    /**
     * Merchant short name code
     * @type {string}
     * @memberof MerchantInformation
     */
    shortNameCode?: string;
    /**
     * Merchant official name
     * @type {string}
     * @memberof MerchantInformation
     */
    officialName?: string;
    /**
     * Merchant English name
     * @type {string}
     * @memberof MerchantInformation
     */
    englishName?: string;
    /**
     * Merchant local (Indonesian) name
     * @type {string}
     * @memberof MerchantInformation
     */
    localName?: string;
    /**
     * 
     * @type {MerchantCertificateInfo}
     * @memberof MerchantInformation
     */
    certificate?: MerchantCertificateInfo;
    /**
     * 
     * @type {MerchantContactAddress}
     * @memberof MerchantInformation
     */
    registeredAddress?: MerchantContactAddress;
    /**
     * 
     * @type {MerchantContactAddress}
     * @memberof MerchantInformation
     */
    businessAddress?: MerchantContactAddress;
    /**
     * Merchant official telephone number
     * @type {string}
     * @memberof MerchantInformation
     */
    officeTelephone?: string;
    /**
     * Merchant official fax telephone number
     * @type {string}
     * @memberof MerchantInformation
     */
    faxTelephone?: string;
    /**
     * 
     * @type {UserName}
     * @memberof MerchantInformation
     */
    corporateOfficialName?: UserName;
    /**
     * 
     * @type {MerchantCorporateCertificate}
     * @memberof MerchantInformation
     */
    corporateCertificate?: MerchantCorporateCertificate;
    /**
     * 
     * @type {UserName}
     * @memberof MerchantInformation
     */
    contactOfficialName?: UserName;
    /**
     * 
     * @type {MerchantContactMobileNo}
     * @memberof MerchantInformation
     */
    contactMobileNo?: MerchantContactMobileNo;
    /**
     * Contact telephone number
     * @type {string}
     * @memberof MerchantInformation
     */
    contactTelephone?: string;
    /**
     * 
     * @type {MerchantContactEmail}
     * @memberof MerchantInformation
     */
    contactEmail?: MerchantContactEmail;
    /**
     * Merchant creation time, YYYY-MM-DDTHH:mm:ss+07:00 (GMT+7)
     * @type {string}
     * @memberof MerchantInformation
     */
    createdTime?: string;
    /**
     * Merchant last modified time, YYYY-MM-DDTHH:mm:ss+07:00 (GMT+7)
     * @type {string}
     * @memberof MerchantInformation
     */
    modifiedTime?: string;
    /**
     * Merchant status
     * @type {string}
     * @memberof MerchantInformation
     */
    merchantStatus?: MerchantInformationMerchantStatusEnum;
    /**
     * Registered source platform
     * @type {string}
     * @memberof MerchantInformation
     */
    registerSource?: string;
    /**
     * Size type
     * @type {string}
     * @memberof MerchantInformation
     */
    sizeType?: MerchantInformationSizeTypeEnum;
    /**
     * Merchant platform identifier
     * @type {string}
     * @memberof MerchantInformation
     */
    platformMid?: string;
    /**
     * Tax number (NPWP), 15 digits
     * @type {string}
     * @memberof MerchantInformation
     */
    taxNo?: string;
    /**
     * Merchant account list (present when `isQueryAccount` is true in request)
     * @type {Array<MerchantAccountInfo>}
     * @memberof MerchantInformation
     */
    accounts?: Array<MerchantAccountInfo>;
    /**
     * Brand name on legal name or tax name
     * @type {string}
     * @memberof MerchantInformation
     */
    brandName?: string;
    /**
     * 
     * @type {MerchantContactAddress}
     * @memberof MerchantInformation
     */
    taxAddress?: MerchantContactAddress;
}


/**
 * @export
 */
export const MerchantInformationMerchantTypeEnum = {
    Individual: 'INDIVIDUAL',
    Corporation: 'CORPORATION',
    FinancialInst: 'FINANCIAL_INST'
} as const;
export type MerchantInformationMerchantTypeEnum = typeof MerchantInformationMerchantTypeEnum[keyof typeof MerchantInformationMerchantTypeEnum] | '';

/**
 * @export
 */
export const MerchantInformationMerchantSubTypeEnum = {
    CompanyType22: 'COMPANY_TYPE_22',
    CompanyType31: 'COMPANY_TYPE_31',
    CompanyType41: 'COMPANY_TYPE_41'
} as const;
export type MerchantInformationMerchantSubTypeEnum = typeof MerchantInformationMerchantSubTypeEnum[keyof typeof MerchantInformationMerchantSubTypeEnum] | '';

/**
 * @export
 */
export const MerchantInformationMerchantStatusEnum = {
    Pending: 'PENDING',
    Active: 'ACTIVE',
    Frozen: 'FROZEN'
} as const;
export type MerchantInformationMerchantStatusEnum = typeof MerchantInformationMerchantStatusEnum[keyof typeof MerchantInformationMerchantStatusEnum] | '';

/**
 * @export
 */
export const MerchantInformationSizeTypeEnum = {
    Umi: 'UMI',
    Uke: 'UKE',
    Ume: 'UME',
    Ube: 'UBE',
    Ure: 'URE'
} as const;
export type MerchantInformationSizeTypeEnum = typeof MerchantInformationSizeTypeEnum[keyof typeof MerchantInformationSizeTypeEnum] | '';


/**
 * Check if a given object implements the MerchantInformation interface.
 */
export function instanceOfMerchantInformation(value: object): value is MerchantInformation {
    return true;
}

export function MerchantInformationFromJSON(json: any): MerchantInformation {
    return MerchantInformationFromJSONTyped(json, false);
}

export function MerchantInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'merchantType': json['merchantType'] == null ? undefined : json['merchantType'],
        'merchantSubType': json['merchantSubType'] == null ? undefined : json['merchantSubType'],
        'mccCodes': json['mccCodes'] == null ? undefined : json['mccCodes'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'logoUrlMap': json['logoUrlMap'] == null ? undefined : json['logoUrlMap'],
        'shortNameCode': json['shortNameCode'] == null ? undefined : json['shortNameCode'],
        'officialName': json['officialName'] == null ? undefined : json['officialName'],
        'englishName': json['englishName'] == null ? undefined : json['englishName'],
        'localName': json['localName'] == null ? undefined : json['localName'],
        'certificate': json['certificate'] == null ? undefined : MerchantCertificateInfoFromJSON(json['certificate']),
        'registeredAddress': json['registeredAddress'] == null ? undefined : MerchantContactAddressFromJSON(json['registeredAddress']),
        'businessAddress': json['businessAddress'] == null ? undefined : MerchantContactAddressFromJSON(json['businessAddress']),
        'officeTelephone': json['officeTelephone'] == null ? undefined : json['officeTelephone'],
        'faxTelephone': json['faxTelephone'] == null ? undefined : json['faxTelephone'],
        'corporateOfficialName': json['corporateOfficialName'] == null ? undefined : UserNameFromJSON(json['corporateOfficialName']),
        'corporateCertificate': json['corporateCertificate'] == null ? undefined : MerchantCorporateCertificateFromJSON(json['corporateCertificate']),
        'contactOfficialName': json['contactOfficialName'] == null ? undefined : UserNameFromJSON(json['contactOfficialName']),
        'contactMobileNo': json['contactMobileNo'] == null ? undefined : MerchantContactMobileNoFromJSON(json['contactMobileNo']),
        'contactTelephone': json['contactTelephone'] == null ? undefined : json['contactTelephone'],
        'contactEmail': json['contactEmail'] == null ? undefined : MerchantContactEmailFromJSON(json['contactEmail']),
        'createdTime': json['createdTime'] == null ? undefined : json['createdTime'],
        'modifiedTime': json['modifiedTime'] == null ? undefined : json['modifiedTime'],
        'merchantStatus': json['merchantStatus'] == null ? undefined : json['merchantStatus'],
        'registerSource': json['registerSource'] == null ? undefined : json['registerSource'],
        'sizeType': json['sizeType'] == null ? undefined : json['sizeType'],
        'platformMid': json['platformMid'] == null ? undefined : json['platformMid'],
        'taxNo': json['taxNo'] == null ? undefined : json['taxNo'],
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(MerchantAccountInfoFromJSON)),
        'brandName': json['brandName'] == null ? undefined : json['brandName'],
        'taxAddress': json['taxAddress'] == null ? undefined : MerchantContactAddressFromJSON(json['taxAddress']),
    };
}

export function MerchantInformationToJSON(json: any): MerchantInformation {
    return MerchantInformationToJSONTyped(json, false);
}

export function MerchantInformationToJSONTyped(value?: MerchantInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'merchantId': value['merchantId'],
        'merchantType': value['merchantType'],
        'merchantSubType': value['merchantSubType'],
        'mccCodes': value['mccCodes'],
        'logoUrl': value['logoUrl'],
        'logoUrlMap': value['logoUrlMap'],
        'shortNameCode': value['shortNameCode'],
        'officialName': value['officialName'],
        'englishName': value['englishName'],
        'localName': value['localName'],
        'certificate': MerchantCertificateInfoToJSON(value['certificate']),
        'registeredAddress': MerchantContactAddressToJSON(value['registeredAddress']),
        'businessAddress': MerchantContactAddressToJSON(value['businessAddress']),
        'officeTelephone': value['officeTelephone'],
        'faxTelephone': value['faxTelephone'],
        'corporateOfficialName': UserNameToJSON(value['corporateOfficialName']),
        'corporateCertificate': MerchantCorporateCertificateToJSON(value['corporateCertificate']),
        'contactOfficialName': UserNameToJSON(value['contactOfficialName']),
        'contactMobileNo': MerchantContactMobileNoToJSON(value['contactMobileNo']),
        'contactTelephone': value['contactTelephone'],
        'contactEmail': MerchantContactEmailToJSON(value['contactEmail']),
        'createdTime': value['createdTime'],
        'modifiedTime': value['modifiedTime'],
        'merchantStatus': value['merchantStatus'],
        'registerSource': value['registerSource'],
        'sizeType': value['sizeType'],
        'platformMid': value['platformMid'],
        'taxNo': value['taxNo'],
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(MerchantAccountInfoToJSON)),
        'brandName': value['brandName'],
        'taxAddress': MerchantContactAddressToJSON(value['taxAddress']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    phoneNumber: {
        maxLength: 64,
    },
    merchantId: {
        maxLength: 21,
    },
    merchantType: {
        maxLength: 14,
    },
    merchantSubType: {
        maxLength: 32,
    },
    shortNameCode: {
        maxLength: 16,
    },
    officialName: {
        maxLength: 128,
    },
    englishName: {
        maxLength: 128,
    },
    localName: {
        maxLength: 128,
    },
    officeTelephone: {
        maxLength: 64,
    },
    faxTelephone: {
        maxLength: 64,
    },
    contactTelephone: {
        maxLength: 32,
    },
    createdTime: {
        maxLength: 25,
    },
    modifiedTime: {
        maxLength: 25,
    },
    merchantStatus: {
        maxLength: 7,
    },
    registerSource: {
        maxLength: 256,
    },
    sizeType: {
        maxLength: 3,
    },
    platformMid: {
        maxLength: 64,
    },
    taxNo: {
        maxLength: 15,
        pattern: new RegExp('/^[0-9]{15}$/'.slice(1, -1)),
    },
    brandName: {
        maxLength: 256,
    },
}

export function validateMerchantInformation(value: MerchantInformation): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('phoneNumber', value.phoneNumber, propertyValidationAttributesMap['phoneNumber']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantId', value.merchantId, propertyValidationAttributesMap['merchantId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantType', value.merchantType, propertyValidationAttributesMap['merchantType']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantSubType', value.merchantSubType, propertyValidationAttributesMap['merchantSubType']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('shortNameCode', value.shortNameCode, propertyValidationAttributesMap['shortNameCode']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('officialName', value.officialName, propertyValidationAttributesMap['officialName']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('englishName', value.englishName, propertyValidationAttributesMap['englishName']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('localName', value.localName, propertyValidationAttributesMap['localName']));

    validationErrorContexts.push(...validateMerchantCertificateInfo(value.certificate));

    validationErrorContexts.push(...validateMerchantContactAddress(value.registeredAddress));

    validationErrorContexts.push(...validateMerchantContactAddress(value.businessAddress));

    validationErrorContexts.push(...ValidationUtil.validateProperty('officeTelephone', value.officeTelephone, propertyValidationAttributesMap['officeTelephone']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('faxTelephone', value.faxTelephone, propertyValidationAttributesMap['faxTelephone']));

    validationErrorContexts.push(...validateUserName(value.corporateOfficialName));

    validationErrorContexts.push(...validateMerchantCorporateCertificate(value.corporateCertificate));

    validationErrorContexts.push(...validateUserName(value.contactOfficialName));

    validationErrorContexts.push(...validateMerchantContactMobileNo(value.contactMobileNo));

    validationErrorContexts.push(...ValidationUtil.validateProperty('contactTelephone', value.contactTelephone, propertyValidationAttributesMap['contactTelephone']));

    validationErrorContexts.push(...validateMerchantContactEmail(value.contactEmail));

    validationErrorContexts.push(...ValidationUtil.validateProperty('createdTime', value.createdTime, propertyValidationAttributesMap['createdTime']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('modifiedTime', value.modifiedTime, propertyValidationAttributesMap['modifiedTime']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('merchantStatus', value.merchantStatus, propertyValidationAttributesMap['merchantStatus']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('registerSource', value.registerSource, propertyValidationAttributesMap['registerSource']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('sizeType', value.sizeType, propertyValidationAttributesMap['sizeType']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('platformMid', value.platformMid, propertyValidationAttributesMap['platformMid']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('taxNo', value.taxNo, propertyValidationAttributesMap['taxNo']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('brandName', value.brandName, propertyValidationAttributesMap['brandName']));

    validationErrorContexts.push(...validateMerchantContactAddress(value.taxAddress));

    return validationErrorContexts;
}
