/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
/**
 * Business fields mapped to `request.body` in the JSON envelope (head/signature are handled by the client/runtime).
 * @export
 * @interface QueryAssetCardListRequest
 */
export interface QueryAssetCardListRequest {
    /**
     * User identifier or merchant identifier
     * @type {string}
     * @memberof QueryAssetCardListRequest
     */
    memberId: string;
    /**
     * Asset card bind identifier
     * @type {string}
     * @memberof QueryAssetCardListRequest
     */
    bindingId?: string;
    /**
     * Return only active cards when `"true"`
     * @type {string}
     * @memberof QueryAssetCardListRequest
     */
    enableOnly?: QueryAssetCardListRequestEnableOnlyEnum;
    /**
     * Contact biz type list (`ContactBizTypeEnum`)
     * @type {Array<string>}
     * @memberof QueryAssetCardListRequest
     */
    contactBizTypeList?: Array<QueryAssetCardListRequestContactBizTypeListEnum>;
    /**
     * Asset type list (`AssetCardTypeEnum`)
     * @type {Array<string>}
     * @memberof QueryAssetCardListRequest
     */
    assetTypeList?: Array<QueryAssetCardListRequestAssetTypeListEnum>;
}


/**
 * @export
 */
export const QueryAssetCardListRequestEnableOnlyEnum = {
    True: 'true',
    False: 'false'
} as const;
export type QueryAssetCardListRequestEnableOnlyEnum = typeof QueryAssetCardListRequestEnableOnlyEnum[keyof typeof QueryAssetCardListRequestEnableOnlyEnum] | '';

/**
 * @export
 */
export const QueryAssetCardListRequestContactBizTypeListEnum = {
    TransferHis: 'TRANSFER_HIS',
    DirectTransfer: 'DIRECT_TRANSFER',
    GeneralCard: 'GENERAL_CARD',
    DirectpayCard: 'DIRECTPAY_CARD',
    PaymentCard: 'PAYMENT_CARD',
    CashoutCard: 'CASHOUT_CARD',
    ImpsAccount: 'IMPS_ACCOUNT',
    InvestmentAccount: 'INVESTMENT_ACCOUNT'
} as const;
export type QueryAssetCardListRequestContactBizTypeListEnum = typeof QueryAssetCardListRequestContactBizTypeListEnum[keyof typeof QueryAssetCardListRequestContactBizTypeListEnum] | '';

/**
 * @export
 */
export const QueryAssetCardListRequestAssetTypeListEnum = {
    CheckingAccount: 'CHECKING_ACCOUNT',
    SavingsAccount: 'SAVINGS_ACCOUNT',
    LoanAccount: 'LOAN_ACCOUNT',
    ImpsAccount: 'IMPS_ACCOUNT',
    DebitCard: 'DEBIT_CARD',
    CreditCard: 'CREDIT_CARD',
    SecuredCreditCard: 'SECURED_CREDIT_CARD',
    VaAccount: 'VA_ACCOUNT',
    OtcAccount: 'OTC_ACCOUNT',
    RefundAccount: 'REFUND_ACCOUNT',
    CreditAccount: 'CREDIT_ACCOUNT',
    Loan: 'LOAN',
    MutualFundsAccount: 'MUTUAL_FUNDS_ACCOUNT',
    Investment: 'INVESTMENT'
} as const;
export type QueryAssetCardListRequestAssetTypeListEnum = typeof QueryAssetCardListRequestAssetTypeListEnum[keyof typeof QueryAssetCardListRequestAssetTypeListEnum] | '';


/**
 * Check if a given object implements the QueryAssetCardListRequest interface.
 */
export function instanceOfQueryAssetCardListRequest(value: object): value is QueryAssetCardListRequest {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function QueryAssetCardListRequestFromJSON(json: any): QueryAssetCardListRequest {
    return QueryAssetCardListRequestFromJSONTyped(json, false);
}

export function QueryAssetCardListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryAssetCardListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'],
        'bindingId': json['bindingId'] == null ? undefined : json['bindingId'],
        'enableOnly': json['enableOnly'] == null ? undefined : json['enableOnly'],
        'contactBizTypeList': json['contactBizTypeList'] == null ? undefined : json['contactBizTypeList'],
        'assetTypeList': json['assetTypeList'] == null ? undefined : json['assetTypeList'],
    };
}

export function QueryAssetCardListRequestToJSON(json: any): QueryAssetCardListRequest {
    return QueryAssetCardListRequestToJSONTyped(json, false);
}

export function QueryAssetCardListRequestToJSONTyped(value?: QueryAssetCardListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberId': value['memberId'],
        'bindingId': value['bindingId'],
        'enableOnly': value['enableOnly'],
        'contactBizTypeList': value['contactBizTypeList'],
        'assetTypeList': value['assetTypeList'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
    memberId: {
        maxLength: 21,
    },
    bindingId: {
        maxLength: 32,
    },
    enableOnly: {
        maxLength: 5,
    },
}

export function validateQueryAssetCardListRequest(value: QueryAssetCardListRequest): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...ValidationUtil.validateProperty('memberId', value.memberId, propertyValidationAttributesMap['memberId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('bindingId', value.bindingId, propertyValidationAttributesMap['bindingId']));

    validationErrorContexts.push(...ValidationUtil.validateProperty('enableOnly', value.enableOnly, propertyValidationAttributesMap['enableOnly']));

    return validationErrorContexts;
}
