/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { MerchantInformation } from './MerchantInformation';
import {
    validateMerchantInformation,
    MerchantInformationFromJSON,
    MerchantInformationFromJSONTyped,
    MerchantInformationToJSON,
    MerchantInformationToJSONTyped,
} from './MerchantInformation';
import type { MemberAssetResultInfo } from './MemberAssetResultInfo';
import {
    validateMemberAssetResultInfo,
    MemberAssetResultInfoFromJSON,
    MemberAssetResultInfoFromJSONTyped,
    MemberAssetResultInfoToJSON,
    MemberAssetResultInfoToJSONTyped,
} from './MemberAssetResultInfo';

/**
 * Response body (`resultInfo` and `merchantInformation` optional per API contract)
 * @export
 * @interface QueryMerchantInfoResponseResponseBody
 */
export interface QueryMerchantInfoResponseResponseBody {
    /**
     * 
     * @type {MemberAssetResultInfo}
     * @memberof QueryMerchantInfoResponseResponseBody
     */
    resultInfo?: MemberAssetResultInfo;
    /**
     * 
     * @type {MerchantInformation}
     * @memberof QueryMerchantInfoResponseResponseBody
     */
    merchantInformation?: MerchantInformation;
}

/**
 * Check if a given object implements the QueryMerchantInfoResponseResponseBody interface.
 */
export function instanceOfQueryMerchantInfoResponseResponseBody(value: object): value is QueryMerchantInfoResponseResponseBody {
    return true;
}

export function QueryMerchantInfoResponseResponseBodyFromJSON(json: any): QueryMerchantInfoResponseResponseBody {
    return QueryMerchantInfoResponseResponseBodyFromJSONTyped(json, false);
}

export function QueryMerchantInfoResponseResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMerchantInfoResponseResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'resultInfo': json['resultInfo'] == null ? undefined : MemberAssetResultInfoFromJSON(json['resultInfo']),
        'merchantInformation': json['merchantInformation'] == null ? undefined : MerchantInformationFromJSON(json['merchantInformation']),
    };
}

export function QueryMerchantInfoResponseResponseBodyToJSON(json: any): QueryMerchantInfoResponseResponseBody {
    return QueryMerchantInfoResponseResponseBodyToJSONTyped(json, false);
}

export function QueryMerchantInfoResponseResponseBodyToJSONTyped(value?: QueryMerchantInfoResponseResponseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultInfo': MemberAssetResultInfoToJSON(value['resultInfo']),
        'merchantInformation': MerchantInformationToJSON(value['merchantInformation']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
}

export function validateQueryMerchantInfoResponseResponseBody(value: QueryMerchantInfoResponseResponseBody): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateMemberAssetResultInfo(value.resultInfo));

    validationErrorContexts.push(...validateMerchantInformation(value.merchantInformation));

    return validationErrorContexts;
}
