/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { ResultInfo } from './ResultInfo';
import {
    validateResultInfo,
    ResultInfoFromJSON,
    ResultInfoFromJSONTyped,
    ResultInfoToJSON,
    ResultInfoToJSONTyped,
} from './ResultInfo';
import type { MerchantResourceInformation } from './MerchantResourceInformation';
import {
    validateMerchantResourceInformation,
    MerchantResourceInformationFromJSON,
    MerchantResourceInformationFromJSONTyped,
    MerchantResourceInformationToJSON,
    MerchantResourceInformationToJSONTyped,
} from './MerchantResourceInformation';

/**
 * 
 * @export
 * @interface QueryMerchantResourceResponseResponseBody
 */
export interface QueryMerchantResourceResponseResponseBody {
    /**
     * 
     * @type {ResultInfo}
     * @memberof QueryMerchantResourceResponseResponseBody
     */
    resultInfo: ResultInfo;
    /**
     * Merchant resource information list - will be filled if success
     * @type {Array<MerchantResourceInformation>}
     * @memberof QueryMerchantResourceResponseResponseBody
     */
    merchantResourceInformations?: Array<MerchantResourceInformation>;
}

/**
 * Check if a given object implements the QueryMerchantResourceResponseResponseBody interface.
 */
export function instanceOfQueryMerchantResourceResponseResponseBody(value: object): value is QueryMerchantResourceResponseResponseBody {
    if (!('resultInfo' in value) || value['resultInfo'] === undefined) return false;
    return true;
}

export function QueryMerchantResourceResponseResponseBodyFromJSON(json: any): QueryMerchantResourceResponseResponseBody {
    return QueryMerchantResourceResponseResponseBodyFromJSONTyped(json, false);
}

export function QueryMerchantResourceResponseResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMerchantResourceResponseResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'resultInfo': ResultInfoFromJSON(json['resultInfo']),
        'merchantResourceInformations': json['merchantResourceInformations'] == null ? undefined : ((json['merchantResourceInformations'] as Array<any>).map(MerchantResourceInformationFromJSON)),
    };
}

export function QueryMerchantResourceResponseResponseBodyToJSON(json: any): QueryMerchantResourceResponseResponseBody {
    return QueryMerchantResourceResponseResponseBodyToJSONTyped(json, false);
}

export function QueryMerchantResourceResponseResponseBodyToJSONTyped(value?: QueryMerchantResourceResponseResponseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultInfo': ResultInfoToJSON(value['resultInfo']),
        'merchantResourceInformations': value['merchantResourceInformations'] == null ? undefined : ((value['merchantResourceInformations'] as Array<any>).map(MerchantResourceInformationToJSON)),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
}

export function validateQueryMerchantResourceResponseResponseBody(value: QueryMerchantResourceResponseResponseBody): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateResultInfo(value.resultInfo));

    return validationErrorContexts;
}
