/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { QueryMerchantInfoResponseResponseBody } from './QueryMerchantInfoResponseResponseBody';
import {
    validateQueryMerchantInfoResponseResponseBody,
    QueryMerchantInfoResponseResponseBodyFromJSON,
    QueryMerchantInfoResponseResponseBodyFromJSONTyped,
    QueryMerchantInfoResponseResponseBodyToJSON,
    QueryMerchantInfoResponseResponseBodyToJSONTyped,
} from './QueryMerchantInfoResponseResponseBody';
import type { QueryMerchantInfoResponseResponseHead } from './QueryMerchantInfoResponseResponseHead';
import {
    validateQueryMerchantInfoResponseResponseHead,
    QueryMerchantInfoResponseResponseHeadFromJSON,
    QueryMerchantInfoResponseResponseHeadFromJSONTyped,
    QueryMerchantInfoResponseResponseHeadToJSON,
    QueryMerchantInfoResponseResponseHeadToJSONTyped,
} from './QueryMerchantInfoResponseResponseHead';

/**
 * 
 * @export
 * @interface QueryMerchantInfoResponseResponse
 */
export interface QueryMerchantInfoResponseResponse {
    /**
     * 
     * @type {QueryMerchantInfoResponseResponseHead}
     * @memberof QueryMerchantInfoResponseResponse
     */
    head?: QueryMerchantInfoResponseResponseHead;
    /**
     * 
     * @type {QueryMerchantInfoResponseResponseBody}
     * @memberof QueryMerchantInfoResponseResponse
     */
    body?: QueryMerchantInfoResponseResponseBody;
}

/**
 * Check if a given object implements the QueryMerchantInfoResponseResponse interface.
 */
export function instanceOfQueryMerchantInfoResponseResponse(value: object): value is QueryMerchantInfoResponseResponse {
    return true;
}

export function QueryMerchantInfoResponseResponseFromJSON(json: any): QueryMerchantInfoResponseResponse {
    return QueryMerchantInfoResponseResponseFromJSONTyped(json, false);
}

export function QueryMerchantInfoResponseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMerchantInfoResponseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'head': json['head'] == null ? undefined : QueryMerchantInfoResponseResponseHeadFromJSON(json['head']),
        'body': json['body'] == null ? undefined : QueryMerchantInfoResponseResponseBodyFromJSON(json['body']),
    };
}

export function QueryMerchantInfoResponseResponseToJSON(json: any): QueryMerchantInfoResponseResponse {
    return QueryMerchantInfoResponseResponseToJSONTyped(json, false);
}

export function QueryMerchantInfoResponseResponseToJSONTyped(value?: QueryMerchantInfoResponseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'head': QueryMerchantInfoResponseResponseHeadToJSON(value['head']),
        'body': QueryMerchantInfoResponseResponseBodyToJSON(value['body']),
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
}

export function validateQueryMerchantInfoResponseResponse(value: QueryMerchantInfoResponseResponse): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateQueryMerchantInfoResponseResponseHead(value.head));

    validationErrorContexts.push(...validateQueryMerchantInfoResponseResponseBody(value.body));

    return validationErrorContexts;
}
