/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by DANA Indonesia.
 * Do not edit the class manually.
 */

import type { PropertyValidationAttribute, ValidationErrorContext } from '../../../runtime';
import { mapValues, ValidationUtil } from '../../../runtime';
import type { UpdateShopResponseResponse } from './UpdateShopResponseResponse';
import {
    validateUpdateShopResponseResponse,
    UpdateShopResponseResponseFromJSON,
    UpdateShopResponseResponseFromJSONTyped,
    UpdateShopResponseResponseToJSON,
    UpdateShopResponseResponseToJSONTyped,
} from './UpdateShopResponseResponse';

/**
 * 
 * @export
 * @interface UpdateShopResponse
 */
export interface UpdateShopResponse {
    /**
     * 
     * @type {UpdateShopResponseResponse}
     * @memberof UpdateShopResponse
     */
    response: UpdateShopResponseResponse;
    /**
     * Signature
     * @type {string}
     * @memberof UpdateShopResponse
     */
    signature?: string;
}

/**
 * Check if a given object implements the UpdateShopResponse interface.
 */
export function instanceOfUpdateShopResponse(value: object): value is UpdateShopResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    return true;
}

export function UpdateShopResponseFromJSON(json: any): UpdateShopResponse {
    return UpdateShopResponseFromJSONTyped(json, false);
}

export function UpdateShopResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateShopResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': UpdateShopResponseResponseFromJSON(json['response']),
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function UpdateShopResponseToJSON(json: any): UpdateShopResponse {
    return UpdateShopResponseToJSONTyped(json, false);
}

export function UpdateShopResponseToJSONTyped(value?: UpdateShopResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': UpdateShopResponseResponseToJSON(value['response']),
        'signature': value['signature'],
    };
}

const propertyValidationAttributesMap: { [property: string]: PropertyValidationAttribute } = {
}

export function validateUpdateShopResponse(value: UpdateShopResponse): ValidationErrorContext[] {
    const validationErrorContexts: ValidationErrorContext[] = [];

    if (value == null) {
        return validationErrorContexts;
    }

    validationErrorContexts.push(...validateUpdateShopResponseResponse(value.response));

    return validationErrorContexts;
}
